In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import importlib
import Regression_utils
importlib.reload(Regression_utils)
from Regression_utils import *

In [2]:
dataset=pd.read_csv("house_price_cleaned.csv")
dataset

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450.0,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600.0,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250.0,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550.0,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260.0,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917.0,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000.0
1456,1457,20,RL,85.0,13175.0,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000.0
1457,1458,70,RL,66.0,9042.0,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,0,5,2010,WD,Normal,266500.0
1458,1459,20,RL,68.0,9717.0,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125.0
1459,1460,20,RL,75.0,9937.0,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500.0

In [3]:
dataset.shape

(1460, 81)

In [4]:
dataset.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 81, dtype: int64

In [5]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450.0,7,5.0,2003,2003,196.0,706.0,...,0,0,0,0,1,0,0,0,1,0
1,2,20,80.0,9600.0,6,7.5,1976,1976,0.0,978.0,...,0,0,0,0,1,0,0,0,1,0
2,3,60,68.0,11250.0,7,5.0,2001,2002,162.0,486.0,...,0,0,0,0,1,0,0,0,1,0
3,4,70,60.0,9550.0,7,5.0,1915,1970,0.0,216.0,...,0,0,0,0,1,0,0,0,0,0
4,5,60,84.0,14260.0,8,5.0,2000,2000,350.0,655.0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917.0,6,5.0,1999,2000,0.0,0.0,...,0,0,0,0,1,0,0,0,1,0
1456,1457,20,85.0,13175.0,6,6.0,1978,1988,119.0,790.0,...,0,0,0,0,1,0,0,0,1,0
1457,1458,70,66.0,9042.0,7,7.5,1941,2006,0.0,275.0,...,0,0,0,0,1,0,0,0,1,0
1458,1459,20,68.0,9717.0,5,6.0,1950,1996,0.0,49.0,...,0,0,0,0,1,0,0,0,1,0
1459,1460,20,75.0,9937.0,5,6.0,1965,1965,0.0,830.0,...,0,0,0,0,1,0,0,0,1,0

In [6]:
indep_X=dataset.drop("SalePrice", axis=1)
indep_X

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450.0,7,5.0,2003,2003,196.0,706.0,...,0,0,0,0,1,0,0,0,1,0
1,2,20,80.0,9600.0,6,7.5,1976,1976,0.0,978.0,...,0,0,0,0,1,0,0,0,1,0
2,3,60,68.0,11250.0,7,5.0,2001,2002,162.0,486.0,...,0,0,0,0,1,0,0,0,1,0
3,4,70,60.0,9550.0,7,5.0,1915,1970,0.0,216.0,...,0,0,0,0,1,0,0,0,0,0
4,5,60,84.0,14260.0,8,5.0,2000,2000,350.0,655.0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917.0,6,5.0,1999,2000,0.0,0.0,...,0,0,0,0,1,0,0,0,1,0
1456,1457,20,85.0,13175.0,6,6.0,1978,1988,119.0,790.0,...,0,0,0,0,1,0,0,0,1,0
1457,1458,70,66.0,9042.0,7,7.5,1941,2006,0.0,275.0,...,0,0,0,0,1,0,0,0,1,0
1458,1459,20,68.0,9717.0,5,6.0,1950,1996,0.0,49.0,...,0,0,0,0,1,0,0,0,1,0
1459,1460,20,75.0,9937.0,5,6.0,1965,1965,0.0,830.0,...,0,0,0,0,1,0,0,0,1,0

In [7]:
dep_Y=dataset["SalePrice"]
dep_Y

0       208500.0
1       181500.0
2       223500.0
3       140000.0
4       250000.0
          ...
1455    175000.0
1456    210000.0
1457    266500.0
1458    142125.0
1459    147500.0
Name: SalePrice, Length: 1460, dtype: float64

In [8]:
# SelectK
summary_k = compare_k_values(
    indep_X,
    dep_Y,
    [35,20,25]
)

print("\nSELECT K")
print(summary_k)


# PCA
summary_pca = compare_pca_values(
    indep_X,
    dep_Y,
    [30,20,25]
)

print("\nPCA")
print(summary_pca)

SELECT K
   K_Value     Best_Model  Best_Score
0       35         Random    0.894786
1       20  GradientBoost    0.877648
2       25  GradientBoost    0.890731

PCA
   PCA Best_Model  Best_Score
0   30     Linear    0.873388
1   20     Linear    0.855337
2   25     Linear    0.871724

In [9]:
# RFE
summary_rfe = compare_rfe_values(
    indep_X,
    dep_Y,
    [15,8,10]
)

print("\nRFE")
print(summary_rfe)

RFE
   RFE Feature_Model  Best_Score
0   15        Linear    0.530094
1   15      Decision    0.897292
2   15        Random    0.898905
3    8        Linear    0.109720
4    8      Decision    0.879183
5    8        Random    0.879927
6   10        Linear    0.110165
7   10      Decision    0.888223
8   10        Random    0.890276

In [12]:
# Combine all results
summary = pd.concat(

[summary_k.rename(columns={"K_Value":"Feature_Count"}).assign(Method="SelectK"),

summary_pca.rename(columns={"PCA":"Feature_Count"}).assign(Method="PCA"),

summary_rfe.rename(columns={"RFE":"Feature_Count","Feature_Model":"Best_Model"}).assign(Method="RFE")],

ignore_index=True)

best = summary.loc[
summary["Best_Score"].idxmax()
]

print("\nFinal Best Result")
print(best)

Final Best Result
Feature_Count          15
Best_Model         Random
Best_Score       0.898905
Method                RFE
Name: 8, dtype: object